### ISSUE TITLE
Pull Watts from a socket that see the watts being used. 

### ISSUE THREAD

**Issue by jhallam3** [1iveowl/VeraControl.PCL#6]
Hi how can I pull the Watt inforamtion from a TKB home TZ88. 

I cant see how to do this. 

Thanks Jon

**Comment by 1iveowl** [comment]
You can't at the moment. 

You will have to fork the project and extend it. It's created in such a manner that extending it is not that hard. See the Readme for details.

If you do feel free to create a PR when you are done.
